# Generated by Django 3.2.12 on 2022-03-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='seungho jeong', max_length=100),
            preserve_default=False,
        ),
    ]
